services:
  db:
    image: postgres:16
    container_name: passkey-wallet-db
    environment:
      POSTGRES_DB: passkey_wallet
      POSTGRES_USER: passkey_user
      POSTGRES_PASSWORD: passkey_password
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:8
    container_name: passkey-wallet-redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
